### ISSUE TITLE
ButtonTheme.bar is Deprecated 

### ISSUE THREAD

**Issue by niklasbartsch** [rodydavis/data_tables#22]

**Comment by niklasbartsch** [comment]
@rodydavis I created a Pull Request #23

**Comment by edwinmacalopu** [comment]
@niklasbartsch  any solution available?

**Comment by rodydavis** [comment]
Did you test the pre release? 👀

**Comment by edwinmacalopu** [comment]
@rodydavis thanks, in pre release it is working

**Comment by rodydavis** [comment]
Perfect!

**Comment by rodydavis** [comment]
fixed with version `1.2.0`
