### ISSUE TITLE
showSelect : false is not working?

### ISSUE THREAD

**Issue by letisoft** [rodydavis/data_tables#29]
Hello,

The lib is great! Thank you very much for your efforts.
I am trying to make the table without selections/checkboxes so I set showSelect : false but still can select?

Thank you!

**Comment by letisoft** [comment]
Hello,

I think I found the issues my self:

in PagedListView - 

return ExpansionTile(
                                  leading: widget.showSelect
                                      ? null
                                      : Checkbox(
should be the opposite?

i StatelessDataTable 

child: DataTable(
                        key: _tableKey,
                        showCheckboxColumn : showCheckboxColumn,
                        columns: columns,
                        sortColumnIndex: sortColumnIndex?

**Comment by rodydavis** [comment]
fixed on latest!
