### ISSUE TITLE
Issues while running Flutter 2.5.1

### ISSUE THREAD

**Issue by ewancmc** [rodydavis/data_tables#45]
My application won't compile or run, attached below is my terminal output:

![image](https://user-images.githubusercontent.com/87296119/135438418-f2901a74-4db9-4896-9547-d9dcefdb7af8.png)

It seems that this issue is also happening with the data_tables example project.

**Comment by rodydavis** [comment]
I'm open to PRs!

**Comment by ewancmc** [comment]
I see this issue is already being handled in this pull request https://github.com/rodydavis/data_tables/pull/39
