### ISSUE TITLE
fix header and size column

### ISSUE THREAD

**Issue by aemsoftwarearacatuba** [rodydavis/data_tables#6]
How to fix the header and determine a size for each column?

**Comment by ethael** [comment]
in following issue they added columnSpacing into DataTable and PaginatedDataTable, so it should be only matter of enabling this parameter also in your API:

https://github.com/flutter/flutter/pull/33628

**Comment by rodydavis** [comment]
I’m in the midst of redoing this packing to make it more powerful and easier to use. I will also pass all options the underlying data table supports

**Comment by ethael** [comment]
great news! do you have any time estimate?

**Comment by advancedtw** [comment]
fixed header would be a great feature I hope you can find a way to enable that feature too.

**Comment by rodydavis** [comment]
Fixed widget header or fixed column header?

**Comment by advancedtw** [comment]
I think it's the column header. the top most with the titles like  dessert| calories| fat.  so that when we scroll down it's always visible.

**Comment by rodydavis** [comment]
Yep! Yeah material doesn’t provide that and I am doing it custom

**Comment by SachinTanpure** [comment]
Is this feature is available now?

**Comment by rodydavis** [comment]
you can now remove the header. it is inside an expanded, so pass it a sized box or constrained box.

**Comment by kevinxxq** [comment]
> you can now remove the header. it is inside an expanded, so pass it a sized box or constrained box.

Any examples for this implementation? Thank you.
