### ISSUE TITLE
Ability to hide SelectAll and Sort actions 

### ISSUE THREAD

**Issue by slavap** [rodydavis/data_tables#7]
![image](https://user-images.githubusercontent.com/4129763/76676164-de1d4900-657d-11ea-815b-d1632e7cad88.png)

It's possible to remove select checkboxes by providing (and for mobile also mobileItemBuilder):
```dart
DataRow.byIndex(
        index: index,
        selected: null,
        onSelectChanged: null,
        cells: <DataCell>[
```
But not possible to hide SelectAll action. Also Sort action should be possible to hide as well.

**Comment by rodydavis** [comment]
Fixed on version `1.3.0`:

```dart
NativeDataTable.fromJson(
        showSelect: false,
        showSort: false,
        rowsPerPage: 40,
        items: _items,
)
```
